{% set name = "xrd_simulator" %}
{% set version = "0.3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xrd_simulator-{{ version }}.tar.gz
  sha256: 6eb05b976fe49c95960b92dfa8d6fa653b82ed33b8f1ae30b2d0097e563c5459

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.9
  run:
    - matplotlib-base
    - meshio
    - numba
    - numpy
    - pycifrw
    - pygalmesh
    - python >=3.8,<3.9
    - scipy
    - dill
    - xfab

test:
  imports:
    - tests
    - xrd_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fable-3dxrd/xrd_simulator
  doc_url: https://fable-3dxrd.github.io/xrd_simulator
  dev_url: https://github.com/fable-3dxrd/xrd_simulator
  summary: Tools for diffraction simulation of s3dxrd type experiments.
  license: MIT
  license_file: LICENSE
  description: |
    The xrd_simulator package defines polycrystals as a mesh of tetrahedral single
    crystals and simulates diffraction as collected by a 2D discretized detector
    array while the sample is rocked around an arbitrary rotation axis.

extra:
  recipe-maintainers:
    - AxelHenningsson
